-- Deshabilitar las restricciones de claves foráneas para evitar errores
ALTER TABLE COMPRAS_PRODUCTOS DROP CONSTRAINT fk_COMPRAS_PRODUCTOS_PRODUCTOS1;
ALTER TABLE COMPRAS_PRODUCTOS DROP CONSTRAINT fk_COMPRAS_PRODUCTOS_COMPRAS1;
ALTER TABLE PRODUCTOS DROP CONSTRAINT fk_PRODUCTOS_CATEGORIAS;
ALTER TABLE COMPRAS DROP CONSTRAINT fk_COMPRAS_CLIENTES1;

-- Eliminar las tablas en orden de dependencias
DROP TABLE COMPRAS_PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE COMPRAS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE CATEGORIAS CASCADE CONSTRAINTS;
