-- -----------------------------------------------------
-- Table "CATEGORIAS"
-- -----------------------------------------------------
CREATE TABLE CATEGORIAS (
  id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(100) NOT NULL,
  estado NUMBER(1) CHECK (estado IN (1, 0)) NOT NULL
);

-- -----------------------------------------------------
-- Table "PRODUCTOS"
-- -----------------------------------------------------
CREATE TABLE PRODUCTOS (
  id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100),
  id_categoria NUMBER NOT NULL,
  codigo_barras VARCHAR2(150),
  precio_venta NUMBER(16,2),
  cantidad_stock NUMBER NOT NULL,
  estado NUMBER(1) CHECK (estado IN (1, 0)),
  CONSTRAINT fk_PRODUCTOS_CATEGORIAS FOREIGN KEY (id_categoria)
    REFERENCES CATEGORIAS (id_categoria)
);

-- -----------------------------------------------------
-- Table "CLIENTES"
-- -----------------------------------------------------
CREATE TABLE CLIENTES (
  id VARCHAR2(20) PRIMARY KEY,
  nombre VARCHAR2(100),
  apellidos VARCHAR2(150),
  celular NUMBER(15),
  direccion VARCHAR2(255),
  correo_electronico VARCHAR2(100)
);

-- -----------------------------------------------------
-- Table "COMPRAS"
-- -----------------------------------------------------
CREATE TABLE COMPRAS (
  id_compra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente VARCHAR2(20) NOT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  medio_pago CHAR(1) CHECK (medio_pago IN ('C', 'D', 'T')),
  comentario VARCHAR2(300),
  estado CHAR(1) CHECK (estado IN ('P', 'C', 'R')),
  CONSTRAINT fk_COMPRAS_CLIENTES1 FOREIGN KEY (id_cliente)
    REFERENCES CLIENTES (id)
);

-- -----------------------------------------------------
-- Table "COMPRAS_PRODUCTOS"
-- -----------------------------------------------------
CREATE TABLE COMPRAS_PRODUCTOS (
  id_compra NUMBER NOT NULL,
  id_producto NUMBER NOT NULL,
  cantidad NUMBER NOT NULL,
  total NUMBER(16,2),
  estado NUMBER(1) CHECK (estado IN (1, 0)),
  PRIMARY KEY (id_compra, id_producto),
  CONSTRAINT fk_COMPRAS_PRODUCTOS_PRODUCTOS1 FOREIGN KEY (id_producto)
    REFERENCES PRODUCTOS (id_producto)
 ,
  CONSTRAINT fk_COMPRAS_PRODUCTOS_COMPRAS1 FOREIGN KEY (id_compra)
    REFERENCES COMPRAS (id_compra)
);


-- Ajustar la secuencia de productos
-- ALTER SEQUENCE ISEQ$$_77404 RESTART START WITH 50;

-- -- Ajustar la secuencia de categorías
-- ALTER SEQUENCE ISEQ$$_77401 RESTART START WITH 8;

-- -- Ajustar la secuencia de compras
-- ALTER SEQUENCE ISEQ$$_77409 RESTART START WITH 1;


